version: "3.9"
services:
  ssl-selfsigned:
    image: alpine
    command:
      - /bin/sh
      - -c
      - |
        cd certs/
        rm key.pem crt.pem
        apk update
        apk add openssl
        openssl req -x509 -newkey rsa:2048 -keyout keytmp.pem -out ssl_crt.pem -days 365 -passout pass:x -subj "/C=IT/ST=Rome/L=Rome/O=PagoPA/OU=T0/CN=localhost"
        openssl rsa -in keytmp.pem -out ssl_key.pem -passin pass:x
    volumes:
      - config:/certs:rw
  keygen:
    image: italia/spid-compliant-certificates:latest
    command: "generator 
      --key-size 3072
      --common-name example
      --days 365
      --entity-id http://localhost:4000
      --locality-name Roma
      --org-id PA:IT-c_h501
      --org-name example
      --sector public
      "
    volumes:
      - config:/certs:rw
    depends_on:
      - ssl-selfsigned
  spid:
    image: "italia/spid-saml-check:1.10.4"
    ports:
      - "8443:8443"
  redis:
    image: wodby/redis:3.2-2.1.5
    environment:
      REDIS_TIMEOUT: 300
      REDIS_TCP_KEEPALIVE: 60
      REDIS_MAXMEMORY: 182m
  web:
    build: .
    command: "npm run dev" 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 3s
    depends_on:
      spid:
        condition: service_started
      keygen:
        condition: service_completed_successfully
    volumes:
      - config:/app/config:ro
      - ./src:/app/src
      - ./examples:/app/examples
      - ./certs:/app/certs
      - ./metadata:/app/metadata
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    env_file:
      - .env
    ports:
      - 4000:4000
      - 9229:9229
volumes:
  config:
